spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: contacts_schema
app:
  init-contacts-enabled: true
  init-contacts-count: 50